// FROZEN FILE — src/engine/types.ts
// Written verbatim from the Connective Sandbox phase 1 build brief.
// Do NOT edit this file in any later phase. It is frozen as of phase 1.
// src/engine/ is pure: it must never import from src/data/, Supabase, or any
// network library.

type WorkflowSpec = {
  name: string
  description: string
  intake: { components: IntakeComponent[] }
  judges: Judge[]
  dashboard: { panels: DashboardPanel[] }
}

type FormField = {
  id: string
  label: string
  type: 'text' | 'textarea' | 'select'
  required?: boolean
  options?: { value: string; label: string }[]
}

type IntakeComponent =
  | { type: 'file_upload'; id: string; label: string; accept: string[]; multiple: boolean; instructions: string }
  | { type: 'chat'; id: string; placeholder: string; opening_message: string }
  | { type: 'button_group'; id: string; label: string; options: { value: string; label: string }[]; multi: boolean }
  | { type: 'text_field'; id: string; label: string; multiline: boolean }
  | { type: 'form'; id: string; fields: FormField[] }

type Judge = {
  id: string
  state_from: string[]
  question: string
  question_type: 'choice' | 'boolean' | 'scalar'
  options?: string[]
  thresholds: { auto: number; review: number }
}

type DashboardPanel =
  | { type: 'confidence_meter'; id: string; judge_id: string; label: string }
  | { type: 'analysis'; id: string; title: string; source: 'llm' | 'judges' }
  | { type: 'monitoring'; id: string; metrics: string[] }
  | { type: 'decision_log'; id: string; limit: number }
  | { type: 'usage_counter'; id: string; label: string }

type JudgeQuestion = {
  id: string
  type: Judge['question_type']
  question: string
  options?: string[]
}

type JudgeAnswer = {
  id: string
  value: string | boolean | number
  probabilities: Record<string, number>
  confidence: number
}

interface JudgeProvider {
  judge(state: string | object, questions: JudgeQuestion[]): Promise<JudgeAnswer[]>
}

export type {
  WorkflowSpec,
  FormField,
  IntakeComponent,
  Judge,
  DashboardPanel,
  JudgeQuestion,
  JudgeAnswer,
}
export type { JudgeProvider }
